### ISSUE TITLE
Docker compose files for your setup

### ISSUE THREAD

**Issue by mrinc** [ajardin/docker-images#43]
Hey,

Do you have any docker compose files for your setup for magento2?

Thanks

**Comment by mrinc** [comment]
Let me be more specific:
Pretty much a ready to go docker-compose file and related files to easily spin up magento2

**Comment by ajardin** [comment]
Hello and sorry for the delay!

Most users of my Magento 2 images do so through [this environment](https://github.com/EmakinaFR/docker-magento2). You can install it in your project thanks to Composer. Please let me know if you need further details. 😉
